
# SEO settings
title: "IT At💜"
title2: "Pinnacle"
description: "We build systems and networks for your business to run faster and more efficient"
keywords: "system, infosec, network, enterprise, myanmar, si"
url: http://pinnaclesi.github.io/
baseurl: "/"

google_analytics: UA-XXXXX-XX
repo: http://github.com/pinnaclesi/thinkspace
twitter_username: "root_pinnaclesi"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Pinnacle SI"
  job      : "SI COMPANY"
  bio      : "We build systems and networks for your business to run faster and more efficient"
  thumb    : /images/author.jpg
  email    : root.pinnaclesi@gmail.com
  url      : http://pinnaclesi.github.io
  github   : http://github.com/pinnaclesi
  twitter  : http://twitter.com/root_pinnaclesi
  # facebook : https://www.facebook.com/profile.php?id=1257583160
  # linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@root_pinnaclesi"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
